### PR TITLE
New: Bookmarks & Prefs URL

### PR DESCRIPTION
**Pull request by Twoure**
Hi @piplongrun 

- Added bookmarks, and icons
- Worked at fixing caching issues when changing base URL in Prefs
- Updated current valid URLs in Prefs
  - ~~kept https version for now, just in case it still works for others~~
- TV Shows are now keyed off of `html.xpath('//div[@class="tv_container"]')`
  - only tv show pages have this class
  - This new _tv show_ key fixes the search function, so regardless if it's a movie or tv show, the correct function will be called to parse its page
- Bookmarks are keyed off of its _media id_.  Taken from thumb URL
- Moved Search to Main Menu, so can access search from all PrimeWire channel pages within the Plex Web Client
- Added search feedback when no results found

Use some or all of this, I don't mind.  Just trying to help.

Regards,

Twoure

### CODE REVIEW

**Comment by Twoure** [comment]
Sorry @piplongrun I made a mistake with the bookmarks.  I forgot to take into account the base URL change with cached bookmarks.  Give me a moment and I'll fix this.

**Comment by Twoure** [comment]
Fixed Bookmark base URL.  It will now change with the URL in the channel preferences.

**Comment by Twoure** [comment]
Finished URL checking for "Site URL".  Now when someone changes the Site URL, it is tested for validity.  If is fails, then the channel will give a popup message and stop until a correct URL is entered.

Also now people can add custom URLs, but only ones that work with the channel will be allowed to run.

Currently there is no code setup for when a URL becomes invalid (if at first is was valid).  When this happens, the user will have to change the URL to a new valid one.  Note whatever content they were trying to watch when the URL became invalid will still be cached on there local Client(s) rendering that video unwatchable until their client(s) clears its cache.  Client cache is separate from Sever cache.

Please note I'm not trying to take over your channel, just trying to help.  I've been using the channel for quite some time now and had been wanting to make these small tweaks for awhile but just didn't have the time till now.  If you don't like/want my changes then no offence taken.

Cheers,
Twoure

**Comment by Twoure** [comment]
Rebased with your master branch, so now there are no conflicts.  Cheers.

**Comment by piplongrun** [comment]
Hey! Thanks for all the work you did on this plugin! Looks really great! I've been busy with other things, but hope to find some time to get my hands dirty again and help or update the code for this plugin!

**Comment by piplongrun** [comment]
1 question: when I first wrote the plugin, there wasn't an easy way to use search and then tell if a search result is a movie or a tv show. Therefore I added a search in both Movies and TV Shows. That way I knew for sure the results were for the correct catagory. Has something on the website changed that makes it possible to use 1 search and tell the difference?

**Comment by Twoure** [comment]
Originally you were checking for `tv=` in the page URL [here](https://github.com/piplongrun/lmwt-kiss.bundle/blob/fdc1f65bbd1b48b64c1e5d29c6d841cccac4cf1b/Contents/Code/__init__.py#L73) but this was not consistent for all tv shows, some were listed in the movies section (and vise versa) and would fail this distinction.  I added the `MediaSubPage` section to properly handle the TV/Movie issue ([ref](https://github.com/Twoure/lmwt-kiss.bundle/blob/master/Contents/Code/__init__.py#L231)).  I found out that if the class `tv_container` ([ref](https://github.com/Twoure/lmwt-kiss.bundle/blob/master/Contents/Code/__init__.py#L250)) was present on the media page then it was organized as a TV Show, otherwise it would be organized as a Movie.

The search uses the same logic as your original with the URL's ([yours](https://github.com/piplongrun/lmwt-kiss.bundle/blob/fdc1f65bbd1b48b64c1e5d29c6d841cccac4cf1b/Contents/Code/__init__.py#L200), [mine](https://github.com/Twoure/lmwt-kiss.bundle/blob/master/Contents/Code/__init__.py#L399)).  I instead give the option to search for Movies/TV Shows after a search has been submitted.  As I said before, the PrimeWire site does not do a good job of being consistent with tagging media as Movies or TV Shows.  This is where my new `MediaSubPage` comes in.  It corrects for any search error produced by PrimeWire.  This fixes the issues your original search was having when movies would pop up in your tv search.  They would be sent to the `MediaSeasons` function which was incorrect for Movies.

Any other questions just ask, I'll do my best to answer.
Glad you like the updates/changes I made.  Hope they serve the community well.

Cheers,
Twoure

**Pull request merged**
